#!/bin/bash

NUMBER=$1
DECIMAL_DIGIT=${#NUMBER}
ROEMIC_NUMBERS=(I V X L C D M)
for (( i=$(($DECIMAL_DIGIT-1))*2; i>=0 ; i-=2 ))
do
	FIRST=${ROEMIC_NUMBERS[$i]}
	SECOND=${ROEMIC_NUMBERS[$i+1]}
	THIRD=${ROEMIC_NUMBERS[$i+2]}
	DECIMAL_ROEMIC=$(($NUMBER%10**($i/2+1)/10**($i/2)))
	PRE_SOLUTION=""
	for (( j=1; j<=$DECIMAL_ROEMIC; j++ ))
	do
		PRE_SOLUTION+=$FIRST
		case $j in
			4) PRE_SOLUTION=$FIRST$SECOND 	;;
			5) PRE_SOLUTION=$SECOND	 	;;
			9) PRE_SOLUTION=$FIRST$THIRD	;;			
		esac
	done
	SOLUTION+=$PRE_SOLUTION
done
echo $SOLUTION
